#ifndef _XSFPDEF_H_
#define _XSFPDEF_H_

#define FF320_MCDU_LF1    "Aircraft.Cockpit.MCDU1.Line1.Click"
#define FF320_MCDU_LF2    "Aircraft.Cockpit.MCDU1.Line3.Click"
#define FF320_MCDU_LF3    "Aircraft.Cockpit.MCDU1.Line5.Click"
#define FF320_MCDU_LF4    "Aircraft.Cockpit.MCDU1.Line7.Click"
#define FF320_MCDU_LF5    "Aircraft.Cockpit.MCDU1.Line9.Click"
#define FF320_MCDU_LF6    "Aircraft.Cockpit.MCDU1.Line11.Click"

#define FF320_MCDU_RF1    "Aircraft.Cockpit.MCDU1.Line2.Click"
#define FF320_MCDU_RF2    "Aircraft.Cockpit.MCDU1.Line4.Click"
#define FF320_MCDU_RF3    "Aircraft.Cockpit.MCDU1.Line6.Click"
#define FF320_MCDU_RF4    "Aircraft.Cockpit.MCDU1.Line8.Click"
#define FF320_MCDU_RF5    "Aircraft.Cockpit.MCDU1.Line10.Click"
#define FF320_MCDU_RF6    "Aircraft.Cockpit.MCDU1.Line12.Click"

#define FF320_MCDU_NUM1   "Aircraft.Cockpit.MCDU1.Num1.Click"
#define FF320_MCDU_NUM2   "Aircraft.Cockpit.MCDU1.Num2.Click"
#define FF320_MCDU_NUM3   "Aircraft.Cockpit.MCDU1.Num3.Click"
#define FF320_MCDU_NUM4   "Aircraft.Cockpit.MCDU1.Num4.Click"
#define FF320_MCDU_NUM5   "Aircraft.Cockpit.MCDU1.Num5.Click"
#define FF320_MCDU_NUM6   "Aircraft.Cockpit.MCDU1.Num6.Click"
#define FF320_MCDU_NUM7   "Aircraft.Cockpit.MCDU1.Num7.Click"
#define FF320_MCDU_NUM8   "Aircraft.Cockpit.MCDU1.Num8.Click"
#define FF320_MCDU_NUM9   "Aircraft.Cockpit.MCDU1.Num9.Click"
#define FF320_MCDU_NUM0   "Aircraft.Cockpit.MCDU1.Num10.Click"
#define FF320_MCDU_POIN   "Aircraft.Cockpit.MCDU1.Num11.Click"
#define FF320_MCDU_PLMI   "Aircraft.Cockpit.MCDU1.Num12.Click"

#define FF320_MCDU_DIR    "Aircraft.Cockpit.MCDU1.Page1.Click"
#define FF320_MCDU_PROG   "Aircraft.Cockpit.MCDU1.Page2.Click"
#define FF320_MCDU_PERF   "Aircraft.Cockpit.MCDU1.Page3.Click"
#define FF320_MCDU_INIT   "Aircraft.Cockpit.MCDU1.Page4.Click"
#define FF320_MCDU_DATA   "Aircraft.Cockpit.MCDU1.Page5.Click"
#define FF320_MCDU_FPLN   "Aircraft.Cockpit.MCDU1.Page6.Click"
#define FF320_MCDU_RAD    "Aircraft.Cockpit.MCDU1.Page7.Click"
#define FF320_MCDU_FUEL   "Aircraft.Cockpit.MCDU1.Page8.Click"
#define FF320_MCDU_SEC    "Aircraft.Cockpit.MCDU1.Page9.Click"
#define FF320_MCDU_ATC    "Aircraft.Cockpit.MCDU1.Page10.Click"
#define FF320_MCDU_MCDU   "Aircraft.Cockpit.MCDU1.Page11.Click"
#define FF320_MCDU_AIR    "Aircraft.Cockpit.MCDU1.Page12.Click"
#define FF320_MCDU_LEFT   "Aircraft.Cockpit.MCDU1.Page13.Click"
#define FF320_MCDU_UP     "Aircraft.Cockpit.MCDU1.Page14.Click"
#define FF320_MCDU_RIGHT  "Aircraft.Cockpit.MCDU1.Page15.Click"
#define FF320_MCDU_DOWN   "Aircraft.Cockpit.MCDU1.Page16.Click"

#define FF320_MCDU_A      "Aircraft.Cockpit.MCDU1.Key1.Click"
#define FF320_MCDU_B      "Aircraft.Cockpit.MCDU1.Key2.Click"
#define FF320_MCDU_C      "Aircraft.Cockpit.MCDU1.Key3.Click"
#define FF320_MCDU_D      "Aircraft.Cockpit.MCDU1.Key4.Click"
#define FF320_MCDU_E      "Aircraft.Cockpit.MCDU1.Key5.Click"
#define FF320_MCDU_F      "Aircraft.Cockpit.MCDU1.Key6.Click"
#define FF320_MCDU_G      "Aircraft.Cockpit.MCDU1.Key7.Click"
#define FF320_MCDU_H      "Aircraft.Cockpit.MCDU1.Key8.Click"
#define FF320_MCDU_I      "Aircraft.Cockpit.MCDU1.Key9.Click"
#define FF320_MCDU_J      "Aircraft.Cockpit.MCDU1.Key10.Click"
#define FF320_MCDU_K      "Aircraft.Cockpit.MCDU1.Key11.Click"
#define FF320_MCDU_L      "Aircraft.Cockpit.MCDU1.Key12.Click"
#define FF320_MCDU_M      "Aircraft.Cockpit.MCDU1.Key13.Click"
#define FF320_MCDU_N      "Aircraft.Cockpit.MCDU1.Key14.Click"
#define FF320_MCDU_O      "Aircraft.Cockpit.MCDU1.Key15.Click"
#define FF320_MCDU_P      "Aircraft.Cockpit.MCDU1.Key16.Click"
#define FF320_MCDU_Q      "Aircraft.Cockpit.MCDU1.Key17.Click"
#define FF320_MCDU_R      "Aircraft.Cockpit.MCDU1.Key18.Click"
#define FF320_MCDU_S      "Aircraft.Cockpit.MCDU1.Key19.Click"
#define FF320_MCDU_T      "Aircraft.Cockpit.MCDU1.Key20.Click"
#define FF320_MCDU_U      "Aircraft.Cockpit.MCDU1.Key21.Click"
#define FF320_MCDU_V      "Aircraft.Cockpit.MCDU1.Key22.Click"
#define FF320_MCDU_W      "Aircraft.Cockpit.MCDU1.Key23.Click"
#define FF320_MCDU_X      "Aircraft.Cockpit.MCDU1.Key24.Click"
#define FF320_MCDU_Y      "Aircraft.Cockpit.MCDU1.Key25.Click"
#define FF320_MCDU_Z      "Aircraft.Cockpit.MCDU1.Key26.Click"
#define FF320_MCDU_SLA    "Aircraft.Cockpit.MCDU1.Key27.Click"
#define FF320_MCDU_SP     "Aircraft.Cockpit.MCDU1.Key28.Click"
#define FF320_MCDU_OVFY   "Aircraft.Cockpit.MCDU1.Key29.Click"
#define FF320_MCDU_CLR    "Aircraft.Cockpit.MCDU1.Key30.Click"

#endif /* _XSFPDEF_H_ */

